# Generated by Django 5.1.7 on 2025-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employe_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
